### ISSUE TITLE
How to define order?

### ISSUE THREAD

**Issue by Shaz3e** [pinceladasdaweb/Socialight#3]
Is there a way to order like |Facebook | Twitter | Linkedin | Pinterest | Buffer
Also please let me know how to add other social network website?

**Comment by wbruno** [comment]
To define and guarantee order, the promise have to be refactored.
To add a new social network, you just have to create a new file like this https://github.com/pinceladasdaweb/Socialight/blob/master/src/google-plus.js

**Comment by pinceladasdaweb** [comment]
This code has been refactored. Look at the example how to set the order: https://github.com/pinceladasdaweb/Socialight/blob/master/example/index.html
